GET http://localhost:8080/events/my-registrations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzMyNDYwNTMwLCJ1c2VySWQiOjExfQ.-3f9_UMlwIQn68t80bUHrMU0o5uXfbFpni4qHnBYGQs

